### ISSUE TITLE
Difference to dvman8bit?

### ISSUE THREAD

**Issue by Darkstylo** [xHeaven/tickMeter#2]
Other than the UI changes, what is the difference compared to the original? I also noticed 1.4 was released from dvman8bit which also includes tickrate graph, will this be included in yours?

Keep up the good work!

**Comment by xHeaven** [comment]
Other than the UI..., 
- I fixed some crashes when opening the program/selecting the network adapter,
- Added/removed some functions, rewrote the IP to Country thing*,
-  I removed the tickrate graph, I didn't really like it, but if you want, I'm going to re-add it, 
- Translated the program to English, and Hungarian, which is my native language, I don't know if he translated it to English.

If you have any feature idea, let me know!

*IPtoCountry: his API won't work after 83 minutes, because the site he used locks the API requests to 1000 per day. The program reaches that limit in 83 minutes (checking the country every 5seconds, so this is 12 requests per minute).
My API will work "forever", because my API locked to 150 requests *per minute* (so no daily limit), but I'm only doing 12 requests per minute. So basically his program won't show the server's country after ~1,5 hours of gaming, but mine will.

**Comment by GrandTheftArmA** [comment]
Thanks for the quick reply, I guess having the tickrate graph as a option available is a nice feature as PUBG tends to have an unstable tickrate in some of the games. Other than that maybe some options to setup the color / text etc for the overlay.

**Comment by Darkstylo** [comment]
Thank you for the quick reply.

I would suggest to re-add the tickRate graph as an option available, as PUBG tends to have inconsistent server performance. 

As a new feature, which would make this one stand out more over the original / source, is to add some options to style the overlay like with MSI Afterburner / HWiNFO.

- Change colors.
- Change text / names.
- Change size,
- Etc..

Other than that keep up the good work!

**Comment by igentuman** [comment]
Hey. Looks like code outdated. I made a lot updates at original repo https://bitbucket.org/dvman8bit/tickmeter/downloads/
Such like:
read/write settings
validate packets with process open connections info (more accurate data)
overlay color changing
updated ping code (more accurate ping)

**Comment by xHeaven** [comment]
> Hey. Looks like code outdated. I made a lot updates at original repo https://bitbucket.org/dvman8bit/tickmeter/downloads/
Such like:
read/write settings
validate packets with process open connections info (more accurate data)
overlay color changing
updated ping code (more accurate ping)


Hey,

thanks for noticing me, I'll update this repository as soon as possible!

Thanks for your work.
